### ISSUE TITLE
Feature request: markdown-it-container support

### ISSUE THREAD

**Issue by CHN-beta** [kaiiiz/hexo-theme-book#10]
Thank you for your great theme.

I noticed the following code in _config.yml in demo.

```
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: info
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger
```

But the dev branch does not support these blocks now. Would it be supported soon? I am looking forward to it.

**Comment by kaiiiz** [comment]
@CHN-beta Actually, these options work very well in book-demo!

Without markdown-it-container:

![image](https://user-images.githubusercontent.com/30596812/73469598-92de1b00-43c1-11ea-8af6-697299dded4e.png)

With markdown-it-container:

![image](https://user-images.githubusercontent.com/30596812/73469184-e7cd6180-43c0-11ea-8f78-99cc3964e68b.png)

You can notice that a `div` wrapper, which is so-called the `container`, is created with a custom class `warning`. After that, you can create these custom css on your own site, even individual posts.

However, because of the scalability of `markdown-it-container`, book theme will not create these custom css by default.

I hope the information helps you and enjoy the theme. 🎉

**Comment by CHN-beta** [comment]
I tried to write css by myself, but I met a weird problem: There are always one more "blank line" under the words.

![image](https://user-images.githubusercontent.com/35858462/73508441-f2b2e100-4416-11ea-9778-5298ea295249.png)
![image](https://user-images.githubusercontent.com/35858462/73508495-17a75400-4417-11ea-881f-4894f0ccadd8.png)

Could you please help me to fix it? (I just started to study css half an hour ago.)

**Comment by CHN-beta** [comment]
I have figured out it.

Thanks again for your great theme.
