### ISSUE TITLE
BUG: menu doesn't work when path contains blank

### ISSUE THREAD

**Issue by CHN-beta** [kaiiiz/hexo-theme-book#13]
Assuming there is two post: `ThisWorksFine.md` and `ThisWillNotWorkWith space.md`.

`menu.md`:

```
# section a
## part a
* [ThisWorksFine](/ThisWorksFine)
* [ThisWillNotWork](/ThisWillNotWorkWith space)
* [ThisAlsoNotWork](/ThisWillNotWorkWith\ space)
```

I am using the last version of dev branch.

**Comment by kaiiiz** [comment]
@CHN-beta Book calls the markdown-it and ejs renderer locally when you click `hexo generate` commands. (ref: scripts/3-render-menu.js)

So the issue comes from the markdown's link syntax, please check: link-destination in [commonMark standard](https://spec.commonmark.org/).

If you really want to use space in link, try:

```
* [ThisAlsoNotWork](/ThisWillNotWorkWith%20space)
```

or

```
* [ThisAlsoNotWork](</ThisWillNotWorkWith space>)
```


I think this is not an issue that related to Book.

**Comment by CHN-beta** [comment]
Thanks. `<...>` works.
