### ISSUE TITLE
When I have more than 22 articles, the side-bar will hide the oldest articles and it only shows latest 22 articles

### ISSUE THREAD

**Issue by Anuluca** [kaiiiz/hexo-theme-book#23]
Hope there re some plans to solve it

**Comment by kaiiiz** [comment]
Can you show me how to reproduce this bug in detail? In the demo site (https://kaiiiz.github.io/hexo-theme-book-demo), there is more than 22 articles, and all posts in sidebar is functional as expected.

**Comment by Anuluca** [comment]
you can see it on Anuluca.gitee.io/me
![QQ截图20200917233739](https://user-images.githubusercontent.com/39253072/93494645-d630ce00-f93f-11ea-82c3-09a4c480cae7.png)
![QQ截图20200917233749](https://user-images.githubusercontent.com/39253072/93494646-d761fb00-f93f-11ea-9a2e-d8555016789e.png)
![QQ截图20200917233826](https://user-images.githubusercontent.com/39253072/93494649-d8932800-f93f-11ea-8e5e-160bad641cfe.png)
![QQ截图20200917233930](https://user-images.githubusercontent.com/39253072/93494652-d9c45500-f93f-11ea-9428-a6c5435aab67.png)

**Comment by Anuluca** [comment]
> you can see it on Anuluca.gitee.io/me
> ![QQ截图20200917233739](https://user-images.githubusercontent.com/39253072/93494645-d630ce00-f93f-11ea-82c3-09a4c480cae7.png)
> ![QQ截图20200917233749](https://user-images.githubusercontent.com/39253072/93494646-d761fb00-f93f-11ea-9a2e-d8555016789e.png)
> ![QQ截图20200917233826](https://user-images.githubusercontent.com/39253072/93494649-d8932800-f93f-11ea-8e5e-160bad641cfe.png)
> ![QQ截图20200917233930](https://user-images.githubusercontent.com/39253072/93494652-d9c45500-f93f-11ea-9428-a6c5435aab67.png)

maybe when I have 22more articles in one submenu it happens

**Comment by kaiiiz** [comment]
I noticed that spectre.css has default value of `accordion` class to `max-height: 50rem` and `overflow: hidden`, which causes the  issue. So I override this value in [ce5be1](https://github.com/kaiiiz/hexo-theme-book/commit/ce5be1d7500722b8bcdc367fc79186c0cfe8ac56).

Please checkout to `dev` branch to get the lastest update. And be aware that I also make the change mention in [issue#16](https://github.com/kaiiiz/hexo-theme-book/issues/16), so home and menu is treated as pages, not posts. Now you need to put your `home.md` and `menu.md` under `/source` folder instead of `/source/_posts` folder to get the correct files during render process.

Please help me test whether there is other bugs or not, thanks for your support.

**Comment by Anuluca** [comment]
> I noticed that spectre.css has default value of `accordion` class to `max-height: 50rem` and `overflow: hidden`, which causes the issue. So I override this value in [ce5be1](https://github.com/kaiiiz/hexo-theme-book/commit/ce5be1d7500722b8bcdc367fc79186c0cfe8ac56).
> 
> Please checkout to `dev` branch to get the lastest update. And be aware that I also make the change mention in [issue#16](https://github.com/kaiiiz/hexo-theme-book/issues/16), so home and menu is treated as pages, not posts. Now you need to put your `home.md` and `menu.md` under `/source` folder instead of `/source/_posts` folder to get the correct files during render process.
> 
> Please help me test whether there is other bugs or not, thanks for your support.

It works nicely,thanks for solving it!
