### ISSUE TITLE
can i have multi-level collapsed menu?

### ISSUE THREAD

**Issue by NulllStack** [kaiiiz/hexo-theme-book#25]

**Comment by kaiiiz** [comment]
No, this theme has not support nested collapsed menu yet. Since the limitation of the framework, the menu is packed during run-time rather then processing by template during render time currently, which is kinda a dirty way. I think I will not implement this feature in this theme, unless someone has a better idea of how to deal with this issue, also with a completely flexible menu solution.

**Comment by NulllStack** [comment]
ah got it, thx :)
